language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
